export component FooterView inherits Rectangle {
    in property <color> color-text;
    in property <color> color-text-muted;
    in-out property <string> status_text;
    in-out property <bool> show-list-view;
    in property <string> wifi_symbol;
    in property <string> current_time;
    height: 30px;
    background: transparent;
    HorizontalLayout {
        alignment: center;
        height: 100%;
        spacing: 15px;
        TouchArea {
            clicked => {
                root.show-list-view = !root.show-list-view;
            }
            horizontal-stretch: 1;
            Rectangle {
                height: 100%;
                horizontal-stretch: 1;
                background: transparent;
                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: root.status_text;
                    color: root.color-text-muted;
                }
            }
        }
    }

    HorizontalLayout {
        alignment: end;
        height: 100%;
        spacing: 15px;
        Text {
            text: root.wifi_symbol;
            vertical-alignment: center;
            color: root.color-text;
        }

        Text {
            text: root.current_time;
            vertical-alignment: center;
            horizontal-alignment: right;
            color: root.color-text-muted;
        }
    }
}
