import { ScrollView } from "std-widgets.slint";

export component LogListView inherits VerticalLayout {
    in property <color> color-text;
    in property <color> color-text-muted;
    in property <[string]> list-items;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    ScrollView {
        width: 100%;
        height: 100%;
        VerticalLayout {
            spacing: 5px;
            padding: 10px;
            for idx in root.list-items.length: Text {
                property <int> reverse-idx: root.list-items.length - 1 - idx;
                text: root.list-items[reverse-idx];
                horizontal-alignment: left;
                color: root.color-text;
                wrap: word-wrap;
                height: 20px;
            }
            if root.list-items.length == 0: Text {
                text: "No updates yet!";
                color: root.color-text-muted;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }
    }
}
