import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 800px;
    height: 480px;
    in-out property <string> fact: "";
    callback update-fact();
    in-out property <string> current_time: "00:00";
    in-out property <string> wifi_symbol: "📶";
    VerticalLayout {
        padding: 5px;
        spacing: 5px;
        HorizontalLayout {
            alignment: end;
            height: 30px;
            spacing: 10px;
            Text {
                text: root.wifi_symbol;
                vertical-alignment: center;
            }

            Text {
                text: root.current_time;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
        }

        GridLayout {
            spacing: 5px;
            Row {
                Button {
                    text: "Button 1";
                }

                Button {
                    text: "Button 2";
                }

                Button {
                    text: "Button 3";
                }

                Button {
                    text: "Button 4";
                }
            }

            Row {
                Button {
                    text: "Button 5";
                }

                Button {
                    text: "Button 6";
                }

                Button {
                    text: "Button 7";
                }

                Button {
                    text: "Button 8";
                }
            }

            Row {
                Button {
                    text: "Button 9";
                }

                Button {
                    text: "Button 10";
                }

                Button {
                    text: "Button 11";
                }

                Button {
                    text: "Button 12";
                }
            }

            Row {
                Button {
                    text: "Button 13";
                }

                Button {
                    text: "Button 14";
                }

                Button {
                    text: "Button 15";
                }

                Button {
                    text: "Button 16";
                }
            }
        }
    }
}
