import { LineEdit, VerticalBox } from "std-widgets.slint";
import "./fonts/MatrixtypeDisplay.ttf";

export component NowView inherits Rectangle {
    in-out property <string> current-date: "MON, JAN 01";
    in-out property <string> current-time: "00:00:00";
    in-out property <string> weather-icon: "☀️"; 
    in-out property <string> weather-temp: "--°C";
    in-out property <string> weather-desc: "Weather: N/A";
    in-out property <string> user-status-icon: "";
    in-out property <string> user-status-text: "";
    property <color> pixel-bg: #000000;
    property <color> pixel-fg-time: #FFFFFF;
    property <color> pixel-fg-date: #A0A0A0;
    property <color> pixel-fg-weather: #C0C0C0;
    property <color> pixel-accent-weather: #FFD700;
    property <string> font-family: "MatrixType Display";
    background: pixel-bg;
    VerticalLayout {

        // Date
        Text {
            text: root.current-date;
            color: pixel-fg-date;
            font-size: 15px;
            font-family: root.font-family;
            font-weight: 400;
            horizontal-alignment: center;
        }

        // Weather
        HorizontalLayout {
            alignment: center;
            Text {
                text: root.weather-icon;
                color: pixel-accent-weather;
                font-size: 20px;
            }

            Text {
                text: root.weather-temp;
                color: pixel-accent-weather;
                font-size: 20px;
                font-family: root.font-family;
                font-weight: 400;
                horizontal-alignment: center;
            }
        }

        // Time
        Text {
            text: root.current-time;
            color: pixel-fg-time;
            font-size: 100px;
            font-family: root.font-family;
            font-weight: 400;
            horizontal-alignment: center;
        }

        Text {
            width: 30%;
            text: root.user-status-icon;
            font-size: 28px;
            font-family: root.font-family;
            font-weight: 400;
            horizontal-alignment: center;
        }

        // Optional: User status text below everything for later
        Text {
            text: root.user-status-text;
            horizontal-alignment: center;
            color: pixel-fg-date;
        }
    }
}
