export component StatusBarView inherits Rectangle {
    // --- Theme Colors (passed from parent) ---
    in property <color> color-statusbar-bg;
    in property <color> color-text-muted;

    // --- State Properties (passed from parent) ---

    height: 25px;
    width: 100%;
    background: root.color-statusbar-bg;
    HorizontalLayout {
        spacing: 15px;
        padding-right: 10px;
        padding-left: 10px;
        width: 100%; // Ensure HorizontalLayout takes full width of StatusBarView
        height: 100%; // Ensure HorizontalLayout takes full height
    }
}
