export component StyledButton inherits TouchArea {
    in property <string> text: "";
    in property <color> base-background: #333333;
    in property <color> hover-background: #444444;
    in property <color> pressed-background: #555555;
    in property <color> text-color: #eeeeee;
    in property <length> border-radius: 8px;
    out property <color> current-background: {
        if (self.pressed) {
            pressed-background
        } else if (self.has-hover) {
            hover-background
        } else {
            base-background
        }
    }
    Rectangle {
        background: current-background;
        border-radius: root.border-radius;
        border-width: 0px;
        horizontal-stretch: 1;
        vertical-stretch: 1;
        min-width: 185px;
        max-width: 185px;
        Text {
            text: root.text;
            color: root.text-color;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}
