export enum WidgetKind {
    text,
    image,
}

export component WidgetItemRenderer inherits Rectangle {
    in property <int> id;
    in property <color> bgcolor;
    in property <string> value_string;
    in property <image> value_image;
    in property <string> title;
    in property <WidgetKind> kind;
    background: bgcolor;
    width: 150px;
    height: 150px;
    VerticalLayout {
        Text {
            text: title;
            vertical-alignment: top;
            horizontal-alignment: center;
            stroke: burlywood;
            padding-top: 10px;
        }

        if root.kind == WidgetKind.text:    
            Text {
            text: value_string;
            vertical-alignment: center;
            horizontal-alignment: center;
            vertical-stretch: 1;
        }
        if root.kind == WidgetKind.image:
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                alignment: center;
                Image {
                    source: value_image;
                    width: 100px;
                    height: 100px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    image-fit: (value_image.width > 100 || value_image.height > 100) ? contain : preserve;
                }
            }
        }
    }
}
